spring:
  profiles:
    active: dev
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  rabbitmq:
    host: localhost  #mq服务器ip,默认为localhost
    port: 5672          #mq服务器port,默认为5672
    username: guest     #mq服务器username,默认为gust
    password: guest     #mq服务器password,默认为guest

logging:
  level:
    com.zhangyun.portalknight.client: info
  config: classpath:logback-spring.xml

fileCloud:
  server:
    nettyPort: 8090
    maxReadLength: 11 #10kb
    rootPath: /Users/zhangyun/Documents/javaProject/FileCloud/serverRootPath

mybatis-plus:
  mapper-locations: classpath:com/zhangyun/filecloud/server/database/mapper/xml/*Mapper.xml
  type-aliases-package: com.zhangyun.filecloud.server.database.entity
  configuration:
    #驼峰命名规则
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# spring web
server:
  port: 8080
