file:
  server:
    host: localhost
    path: /Users/zhangyun/test/target
  client:
    path: /Users/zhangyun/test/source
    maxsize: 10
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_cloud?servertimezone=Asia?Shanghai&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: H2r9P4_f*21L9
